services:
  stock-manager:
    container_name: stock-manager
    image: guicastro26/stock-manager:1.0.0
    build: .
    ports:
      - "8080:8000"
    environment:
      APP_ENV: local
      APP_DEBUG: true

      DB_CONNECTION: pgsql
      DB_HOST: db
      DB_PORT: 5432
      DB_DATABASE: stock
      DB_USERNAME: postgres
      DB_PASSWORD: postgres
    depends_on:
      - db

  db:
    container_name: stock-manager-db
    image: postgres:16
    ports:
      - "5433:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: stock
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata: {}